defaults:
- main
- _self_

df_path: data/interim/metadata.xlsx
save_dir: data/final/smp
train_size: 0.85
seed: 21
classes: |
  - Arteriole lumen
  - Arteriole media
  - Arteriole adventitia
  - Capillary lumen
  - Capillary wall
  - Venula lumen
  - Venule wall
