defaults:
- main
- _self_

data_dir: data/interim
save_dir: data/final
train_size: 0.80
seed: 11
smooth_mask: true
class_names:
- Arteriole lumen
- Arteriole media
- Arteriole adventitia
- Capillary lumen
- Capillary wall
- Venule lumen
- Venule wall
