defaults:
- main
- _self_

project_name: histology_segmentation
data_dir: data/cv/fold_1
classes:
- Arteriole lumen
- Arteriole media
- Arteriole adventitia
- Capillary lumen
- Capillary wall
- Venule lumen
- Venule wall
- Immune cells
- Nerve trunks
architecture: linknet
encoder: efficientnet-b0
optimizer: Adam
input_size: 448
batch_size: 4
lr: 0.00012
epochs: 5
device: cuda
cuda_num: [0]
log_artifacts: true
