defaults:
- main
- _self_

project_name: histology_segmentation
data_dir: data/final
classes:
- Arteriole lumen
- Arteriole media
- Arteriole adventitia
- Capillary lumen
- Capillary wall
- Venule lumen
- Venule wall
- Immune cells
- Nerve trunks
architecture: unet
encoder: resnet50
optimizer: Adam
input_size: 448
batch_size: 16
dropout: 0.5
loss: dice
lr: 0.00012
epochs: 50
device: auto
