defaults:
- main
- _self_

# TODO: check project_name for train and tune settings
#project_name: histology_segmentation
project_name: histology_segmentation/hyperparameter_optimization
data_dir: data/final
classes:
- Arteriole lumen
- Arteriole media
- Arteriole adventitia
- Capillary lumen
- Capillary wall
- Venule lumen
- Venule wall
- Immune cells
- Nerve trunks
architecture: unet
encoder: resnet50
optimizer: Adam
input_size: 448
batch_size: 16
lr: 0.00012
epochs: 50
device: auto
log_artifacts: false
