defaults:
- main
- _self_

project_name: histology_segmentation/hyperparameter_optimization
architecture: unet
encoder:          # TODO: let's keep RESNET50 as the base network and add the recent and SOTA networks
- resnet50
- resnext50_32x4d
- timm-resnest50d
- timm-regnetx_064
- se_resnet50
- xception
- efficientnet-b5
- timm-efficientnet-b5
- timm-efficientnet-lite4
- mit_b2
- timm-mobilenetv3_large_100
- mobilenet_v2
- mobileone_s4
optimizer:
- Adam
- RAdam
- SAdam
- SGD
input_size: 448
batch_size: 8
encoder_depth: 3    # TODO: do we need this parameter?
dropout: 0.5
loss: dice
lr: 0.00012
